### ISSUE TITLE
TypeError: 'instancemethod' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by SeekPoint** [thunlp/OpenNE#16]
mldl@mldlUB1604:~/ub16_prj/OpenNE$ python src/main.py --method node2vec --label-file data/blogCatalog/bc_labels.txt --input data/blogCatalog/bc_adjlist.txt --graph-format adjlist --output vec_all.txt --q 0.25 --p 0.25
Reading...
Traceback (most recent call last):
  File "src/main.py", line 124, in <module>
    main(parse_args())
  File "src/main.py", line 74, in main
    g.read_adjlist(filename=args.input)
  File "/home/mldl/ub16_prj/OpenNE/src/libnrl/graph.py", line 37, in read_adjlist
    self.encode_node()
  File "/home/mldl/ub16_prj/OpenNE/src/libnrl/graph.py", line 27, in encode_node
    self.G.nodes[node]['status'] = ''
TypeError: 'instancemethod' object has no attribute '__getitem__'
mldl@mldlUB1604:~/ub16_prj/OpenNE$

**Comment by cxy229** [comment]
Update your python module`networkx` to version 2.0 or above (e.g. `pip install -U networkx`). 

Because in previous versions of `networkx`, `networkx.Graph.nodes` is a method, not a NodeDataView object and can't be used for data look up. For more information, look at [networkx.Graph.nodes](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.Graph.nodes.html?highlight=nodes#networkx.Graph.nodes).
