### ISSUE TITLE
About wiki dataset

### ISSUE THREAD

**Issue by lancoyy** [thunlp/OpenNE#18]
Hi, I wonder the original source of the data set WIKI. . or the dataset is generate by yourself ?.

**Comment by zzy14** [comment]
Wiki dataset is provided by [LBC project](http://www.cs.umd.edu/~sen/lbc-proj/LBC.html). The original source link is http://linqs.cs.umd.edu/projects/projects/lbc/index.html. But it failed.

**Comment by eriq-augustine** [comment]
I am a member of the lab responsible for the LBC project (although it has since moved from UMD to UCSC).
I don't think this dataset is ours.
No members of this lab know about it, and I can't find the data on our servers.

The LBC project provided three document classification datasets: CiteSeer, Cora, and WebKB.
Both CiteSeer and Cora are commonly used.
I think WebKB was confused with some other Wiki dataset.

If someone has any more provenance information, we can investigate this more.
Otherwise, we should remove the LBC attribution on the Wiki dataset.
