### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by senjed** [thunlp/OpenNE#61]
I get Illegal instruction (core dumped.  tensorflow 1.10 I think you need to update tensorflow version to 1.5 in requirements.py

**Comment by kznovo** [comment]
@senjed 

I had the tensorflow core dumped issue before, but the cause was that my CPU did not support AVX instructions.

https://stackoverflow.com/a/49094955/9006027

After [building tensorflow from source](https://www.tensorflow.org/install/source) using the appropriate config for my CPU the issue went away.

[This stackoverflow question](https://stackoverflow.com/q/37480071/9006027) helped me check whether my CPU supports AVX instructions.

**Comment by Bznkxs** [comment]
Hi senjed and kznovo,
Thanks for your issue and reply. We have migrated OpenNE to PyTorch (check out https://github.com/thunlp/OpenNE/tree/pytorch) and will no longer maintain the TensorFlow version. Sorry for that :-)
