### ISSUE TITLE
KeyError with node2vec

### ISSUE THREAD

**Issue by adityat** [thunlp/OpenNE#88]
Hi, I am facing issues when running node2vec, here's a snippet that causes the error:

```
G = nx.karate_club_graph()
G.to_directed()

g = Graph()
g.G = G
for i,j in g.G.edges():
    g.G[i][j]['weight'] = 1.0
g.encode_node()

model = node2vec.Node2vec(graph=g, path_length=10, num_paths=10, dim=4, workers=2, window=5, dw=False)


```

KeyError: (33, 27)

The same code seems to work properly for all other algorithms (including DeepWalk), so I'm wondering what is causing the error 

Thank you.

**Comment by d12306** [comment]
@adityat , Hi, I am facing the same issue, have you solved this problem?

**Comment by Bznkxs** [comment]
Hi adityat!
Thanks for your issue.
The error occurs because (27, 33) exists but (33, 27) doesn't in g.G.

On using Node2vec, there are two things that you need to take special care of:
1. your graph should be a DiGraph, which means having both edges (i, j) and (j, i) at the same time;
2. your graph node should be str, not int due to implementation issues.

So you might consider using the following code:
```
G = nx.karate_club_graph()

for i,j in G.edges():
    G[i][j]['weight'] = 1.0

G = nx.DiGraph(G)
G = nx.relabel_nodes(G, {i: str(i) for i in G.nodes})

g = Graph()
g.G = G
g.encode_node()

model = node2vec.Node2vec(graph=g, path_length=10, num_paths=10, dim=4, workers=2, window=5, dw=False)
```
